pipelines:
  custom:
    customPipelineWithRunnerStep:
      - step:
          name: Step 1
          runs-on: 
            - 'self.hosted'
            - 'linux.shell'
            - 'linux1'
          script:
            - echo 'This step will run on a self-hosted Linux Shell runner.';
